import {
  Admin,
  Customer,
  Partner,
  Booking,
  ServiceCategory,
  Service,
  DashboardStats,
  BookingStatus,
  PartnerStatus,
  Vendor,
  Area,
} from "./types";

export const MOCK_ADMIN: Admin = {
  id: "admin1",
  name: "Sudeep Chopde",
  email: "admin@homewash.com",
  role: "SUPER_ADMIN",
};

export const MOCK_VENDOR_ADMIN: Admin = {
  id: "v_admin1",
  name: "Rajiv Malhotra",
  email: "rajiv@cleanforce.com",
  role: "VENDOR",
  vendorId: "v1",
};

export const MOCK_STATS: DashboardStats = {
  totalRevenue: 284500,
  revenueChange: 12.5,
  totalBookings: 1248,
  bookingsChange: 8.3,
  activePartners: 47,
  partnersChange: 4.2,
  activeUsers: 3456,
  usersChange: 15.7,
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Priya Sharma",
    phone: "+91 98765 43210",
    email: "priya@email.com",
    totalBookings: 12,
    totalSpent: 15600,
    joinedDate: "2024-08-15",
    lastActive: "2024-02-05",
  },
  {
    id: "c2",
    name: "Amit Patel",
    phone: "+91 88776 55443",
    email: "amit@email.com",
    totalBookings: 8,
    totalSpent: 9800,
    joinedDate: "2024-09-20",
    lastActive: "2024-02-04",
  },
  {
    id: "c3",
    name: "Neha Gupta",
    phone: "+91 77665 44332",
    email: "neha@email.com",
    totalBookings: 5,
    totalSpent: 6200,
    joinedDate: "2024-10-10",
    lastActive: "2024-02-03",
  },
  {
    id: "c4",
    name: "Rahul Verma",
    phone: "+91 66554 33221",
    email: "rahul@email.com",
    totalBookings: 15,
    totalSpent: 22400,
    joinedDate: "2024-07-01",
    lastActive: "2024-02-06",
  },
  {
    id: "c5",
    name: "Sneha Joshi",
    phone: "+91 55443 22110",
    email: "sneha@email.com",
    totalBookings: 3,
    totalSpent: 3800,
    joinedDate: "2024-11-25",
    lastActive: "2024-01-28",
  },
];

export const MOCK_PARTNERS: Partner[] = [
  {
    id: "p1",
    name: "Rajesh Kumar",
    phone: "+91 98765 11111",
    email: "rajesh@email.com",
    status: PartnerStatus.ACTIVE,
    rating: 4.8,
    completedJobs: 127,
    earnings: 89500,
    tier: "GOLD",
    joinedDate: "2024-06-15",
  },
  {
    id: "p2",
    name: "Sunil Yadav",
    phone: "+91 98765 22222",
    email: "sunil@email.com",
    status: PartnerStatus.ACTIVE,
    rating: 4.6,
    completedJobs: 89,
    earnings: 62300,
    tier: "SILVER",
    joinedDate: "2024-07-20",
  },
  {
    id: "p3",
    name: "Vikram Singh",
    phone: "+91 98765 33333",
    email: "vikram@email.com",
    status: PartnerStatus.SUSPENDED,
    rating: 3.9,
    completedJobs: 45,
    earnings: 31200,
    tier: "SILVER",
    joinedDate: "2024-08-10",
  },
  {
    id: "p4",
    name: "Arun Sharma",
    phone: "+91 98765 44444",
    email: "arun@email.com",
    status: PartnerStatus.ONBOARDING,
    rating: 0,
    completedJobs: 0,
    earnings: 0,
    tier: "SILVER",
    joinedDate: "2024-02-01",
  },
  {
    id: "p5",
    name: "Deepak Mishra",
    phone: "+91 98765 55555",
    email: "deepak@email.com",
    status: PartnerStatus.ACTIVE,
    rating: 4.9,
    completedJobs: 203,
    earnings: 142800,
    tier: "PLATINUM",
    joinedDate: "2024-04-05",
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "BK001",
    customerId: "c1",
    customerName: "Priya Sharma",
    partnerId: "p1",
    partnerName: "Rajesh Kumar",
    serviceName: "Deep Home Cleaning",
    amount: 1499,
    status: BookingStatus.IN_PROGRESS,
    scheduledDate: "2024-02-06",
    scheduledTime: "10:00 AM",
    address: "Flat 402, Oberoi Springs, Bandra West",
    createdAt: "2024-02-05",
  },
  {
    id: "BK002",
    customerId: "c2",
    customerName: "Amit Patel",
    partnerId: undefined,
    partnerName: undefined,
    serviceName: "Sofa Cleaning",
    amount: 499,
    status: BookingStatus.PENDING,
    scheduledDate: "2024-02-07",
    scheduledTime: "2:00 PM",
    address: "201, Sea View Apartments, Worli",
    createdAt: "2024-02-06",
  },
  {
    id: "BK003",
    customerId: "c4",
    customerName: "Rahul Verma",
    partnerId: "p5",
    partnerName: "Deepak Mishra",
    serviceName: "Kitchen Deep Clean",
    amount: 999,
    status: BookingStatus.CONFIRMED,
    scheduledDate: "2024-02-06",
    scheduledTime: "3:30 PM",
    address: "C-45, Hiranandani Gardens, Powai",
    createdAt: "2024-02-05",
  },
  {
    id: "BK004",
    customerId: "c3",
    customerName: "Neha Gupta",
    partnerId: "p2",
    partnerName: "Sunil Yadav",
    serviceName: "Bathroom Polish",
    amount: 399,
    status: BookingStatus.COMPLETED,
    scheduledDate: "2024-02-05",
    scheduledTime: "11:00 AM",
    address: "B-12, Raheja Complex, Andheri East",
    createdAt: "2024-02-04",
  },
  {
    id: "BK005",
    customerId: "c5",
    customerName: "Sneha Joshi",
    serviceName: "AC Servicing",
    amount: 699,
    status: BookingStatus.CANCELLED,
    scheduledDate: "2024-02-04",
    scheduledTime: "4:00 PM",
    address: "D-78, Palm Beach Road, Vashi",
    createdAt: "2024-02-03",
  },
];

export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: "cat1",
    name: "Home Cleaning",
    icon: "cleaning_services",
    servicesCount: 8,
  },
  { id: "cat2", name: "Bathroom", icon: "bathroom", servicesCount: 5 },
  { id: "cat3", name: "Kitchen", icon: "kitchen", servicesCount: 6 },
  { id: "cat4", name: "Water Tank", icon: "water_drop", servicesCount: 3 },
  { id: "cat5", name: "Sofa & Carpet", icon: "weekend", servicesCount: 4 },
  { id: "cat6", name: "Car Wash", icon: "directions_car", servicesCount: 5 },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: "s1",
    name: "Deep Home Cleaning",
    categoryId: "cat1",
    price: 1499,
    duration: "3-4 hours",
    isActive: true,
  },
  {
    id: "s2",
    name: "Regular Cleaning",
    categoryId: "cat1",
    price: 799,
    duration: "2 hours",
    isActive: true,
  },
  {
    id: "s3",
    name: "Bathroom Polish",
    categoryId: "cat2",
    price: 399,
    duration: "1 hour",
    isActive: true,
  },
  {
    id: "s4",
    name: "Kitchen Deep Clean",
    categoryId: "cat3",
    price: 999,
    duration: "2 hours",
    isActive: true,
  },
  {
    id: "s5",
    name: "Sofa Cleaning",
    categoryId: "cat5",
    price: 499,
    duration: "1.5 hours",
    isActive: true,
  },
  {
    id: "s6",
    name: "Car Interior Clean",
    categoryId: "cat6",
    price: 599,
    duration: "1 hour",
    isActive: false,
  },
];

export const RECENT_ACTIVITY = [
  {
    type: "booking",
    message: "New booking #BK002 from Amit Patel",
    time: "2 mins ago",
  },
  {
    type: "partner",
    message: "Arun Sharma completed onboarding",
    time: "15 mins ago",
  },
  {
    type: "payment",
    message: "Payment of ₹1,499 received for #BK001",
    time: "32 mins ago",
  },
  {
    type: "alert",
    message: "Partner Vikram Singh marked as suspended",
    time: "1 hour ago",
  },
  {
    type: "booking",
    message: "Booking #BK004 completed successfully",
    time: "2 hours ago",
  },
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "CleanForce Solutions",
    ownerName: "Rajiv Malhotra",
    email: "rajiv@cleanforce.com",
    phone: "+91 99887 76655",
    address: "B-45, Sunshine Towers, Bandra West",
    activeAreas: ["Bandra", "Juhu", "Khar"],
    isActive: true,
    commissionRate: 20,
    partnersCount: 15,
  },
  {
    id: "v2",
    name: "Express Cleaners",
    ownerName: "Sanjay Joshi",
    email: "sanjay@express.com",
    phone: "+91 88776 65544",
    address: "C-12, Green Park, Powai",
    activeAreas: ["Powai", "Hiranandani", "Andheri East"],
    isActive: true,
    commissionRate: 15,
    partnersCount: 10,
  },
  {
    id: "v3",
    name: "Elite Home Services",
    ownerName: "Meera Nair",
    email: "meera@elite.com",
    phone: "+91 77665 54433",
    address: "D-78, Palm Court, Malad West",
    activeAreas: ["Malad", "Kandivali", "Borivali"],
    isActive: false,
    commissionRate: 25,
    partnersCount: 8,
  },
];

export const MOCK_AREAS: Area[] = [
  {
    id: "a1",
    name: "Bandra",
    city: "Mumbai",
    zipCodes: ["400050", "400051"],
    isActive: true,
    vendorsCount: 2,
  },
  {
    id: "a2",
    name: "Powai",
    city: "Mumbai",
    zipCodes: ["400076"],
    isActive: true,
    vendorsCount: 1,
  },
  {
    id: "a3",
    name: "Juhu",
    city: "Mumbai",
    zipCodes: ["400049"],
    isActive: true,
    vendorsCount: 3,
  },
  {
    id: "a4",
    name: "Khar",
    city: "Mumbai",
    zipCodes: ["400052"],
    isActive: false,
    vendorsCount: 0,
  },
];
